### ISSUE TITLE
Error: FileNotFoundException settings.json

### ISSUE THREAD

**Issue by Leeibrah** [rufhausen/brewski#1]
Hi,

My application is not running well because I get his error:
Illuminate \ Contracts \ Filesystem \ FileNotFoundException  settings.json

What are the contents of this file because when i looked it had been added to the /storage/app/.gitignore file or What should be done to overcome this error.

Waiting to hear from you.

**Comment by rufhausen** [comment]
I hope you are not using this app for anything critical as it's very much a work-in-progress. However, the settings.json file should like like the following and it should be located in storage/app/: 
```
{
    "site_name":"Web Site Name",
    "tag_line":"Not a Wordpress Site",
    "admin_email":"email@email.com",
    "posts_per_page":"5",
    "meta_keywords":"",
    "meta_description":"",
    "google_analytics_id":"",
    "twitter_handle":"",
    "google_plus_url":"",
    "linkedin_url":"",
    "facebook_url":"",
    "rss_feed_url":"",
    "page_cache_timeout":"600",
    "recaptcha_public_key":"",
    "recaptcha_private_key":"",
    "disqus_short_name":"",
    "enable_recaptcha":"0",
    "email_username": "",
    "email_password": "",
    "email_smtp_server": "",
    "email_port": ""
}
```

**Comment by Leeibrah** [comment]
Thanks You. Just what I was looking for. I can continue from there.
